// Core domain types for Emerson

export type ProjectStatus = 'setup' | 'outlining' | 'drafting' | 'revising' | 'polishing';

export interface Project {
  id: string;
  name: string;
  genre: string;
  status: ProjectStatus;
  createdAt: Date;
  updatedAt: Date;
  settings: ProjectSettings;
}

export interface ProjectSettings {
  openRouterKey?: string;
  preferredModels: {
    analysis: string;
    writing: string;
    brainstorm: string;
  };
  targetWordCount?: number;
}

// Story structure
export interface Premise {
  logline: string;
  theme: string;
  genre: string;
  tone: string;
  comparables?: string[];
}

export interface BeatSheet {
  beats: Beat[];
}

export interface Beat {
  id: string;
  name: string;
  description: string;
  percentageStart: number;
  percentageEnd: number;
  chapters: string[]; // chapter IDs
}

// Chapters and scenes
export type SceneStatus = 'planned' | 'beat' | 'drafted' | 'revised' | 'complete';

export interface Chapter {
  id: string;
  number: number;
  title: string;
  scenes: Scene[];
  summary?: string;
}

export interface Scene {
  id: string;
  chapterId: string;
  number: number;
  goal: string;
  pov?: string;
  location?: string;
  status: SceneStatus;
  beats?: string; // markdown instructions for writing
  content?: string; // the actual prose
  summary?: string; // post-write summary for context
  wordCount: number;
  issues: Issue[];
}

// Codex (Story Bible)
export type CodexEntryType = 'character' | 'location' | 'item' | 'faction' | 'concept' | 'event';

export interface CodexEntry {
  id: string;
  type: CodexEntryType;
  name: string;
  aliases: string[];
  description: string;
  attributes: Record<string, string>;
  relationships: Relationship[];
  firstAppearance?: string; // scene ID
  tags: string[];
}

export interface Relationship {
  targetId: string;
  type: string;
  description: string;
}

// Analysis / Issues
export type IssueType = 'continuity' | 'foreshadowing' | 'pacing' | 'voice' | 'prose';
export type IssueSeverity = 'blocking' | 'warning' | 'suggestion';

export interface Issue {
  id: string;
  type: IssueType;
  severity: IssueSeverity;
  sceneId: string;
  description: string;
  suggestion?: string;
  resolved: boolean;
}

// Analysis indexes (generated by analysis passes)
export interface ContinuityIndex {
  facts: ContinuityFact[];
  contradictions: Contradiction[];
}

export interface ContinuityFact {
  id: string;
  subject: string;
  attribute: string;
  value: string;
  sceneId: string;
  excerpt: string;
}

export interface Contradiction {
  factIds: [string, string];
  description: string;
}

export interface ForeshadowingIndex {
  setups: ForeshadowingSetup[];
}

export interface ForeshadowingSetup {
  id: string;
  description: string;
  setupSceneId: string;
  payoffSceneId?: string;
  status: 'planted' | 'paid' | 'orphaned';
}

// Context assembly for writing
export interface WritingContext {
  scene: Scene;
  beats: string;
  recentSummaries: string[];
  activeCharacters: CodexEntry[];
  activeLocation?: CodexEntry;
  relevantFacts: ContinuityFact[];
  ripeForeshadowing: ForeshadowingSetup[];
  styleNotes?: string;
}

// OpenRouter types
export interface ModelConfig {
  id: string;
  name: string;
  contextWindow: number;
  costPer1kInput: number;
  costPer1kOutput: number;
}

export interface GenerationRequest {
  model: string;
  systemPrompt: string;
  userPrompt: string;
  maxTokens?: number;
  temperature?: number;
}

export interface GenerationResponse {
  content: string;
  model: string;
  usage: {
    promptTokens: number;
    completionTokens: number;
    cost: number;
  };
}
